name: Windows 2022 ISO
on: workflow_dispatch
jobs:
  build:
    name: Windows 2022 ISO
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        os_build: [ latest ]

    steps:
      - name: Check out ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Select Windows OS build
        shell: pwsh
        run: |
          . .\Get-WindowsUpdateHistory.ps1
          $ChangeHistoryName = "Windows Server 2022"
          
          $OSBuild = '${{matrix.os_build}}'
          if ($OSBuild -eq 'latest') {
            $WindowsUpdate = Get-WindowsUpdateHistory $ChangeHistoryName | Select-Object -First 1
          } else {
            $WindowsUpdate = Get-WindowsUpdateHistory $ChangeHistoryName | Where-Object { $_.Build -eq $OSBuild } | Select-Object -First 1
          }

          if (-Not $WindowsUpdate) {
            throw "Could not find '$ChangeHistoryName' OS Build $OSBuild"
          }

          $OSBuild = $WindowsUpdate.Build
          echo "OS_BUILD=$OSBuild" >> $Env:GITHUB_ENV

          echo "::notice::Name: $ChangeHistoryName"
          echo "::notice::Title: $($WindowsUpdate.Title)"
          echo "::notice::Build: $($WindowsUpdate.Build)"
          echo "::notice::KB: $($WindowsUpdate.KB)"
          echo "::notice::Link: $($WindowsUpdate.Link)"

      - name: Configure runner
        run: |
          docker system prune -a -f
          New-Item "C:\workspace" -ItemType Directory

      - name: Download UUP Media Creator
        shell: pwsh
        run: |
          $DownloadUrl = "https://github.com/gus33000/UUPMediaCreator/releases/download/v3.1.9.2/win-x64-binaries.zip"
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest $DownloadUrl -OutFile .\UUPMediaCreator.zip
          Expand-Archive -Path .\UUPMediaCreator.zip C:\UUPMediaCreator
          echo "PATH=$Env:PATH;C:\UUPMediaCreator" >> $Env:GITHUB_ENV

      - name: Download UUP files
        shell: pwsh
        working-directory: C:\workspace
        run: |
          $OSBuild = $Env:OS_BUILD
          $ReportingVersion = "10.0.${OSBuild}"
          UUPDownload.exe -s StandardServer -r Retail -b Retail -c fe_release -l en-US -t amd64 -v $ReportingVersion

      - name: Create Windows ISO
        shell: pwsh
        working-directory: C:\workspace
        run: |
          $OSBuild = $Env:OS_BUILD
          $UupPath = Get-Item .\10.0.*.*.* | Select-Object -First 1 -ExpandProperty Name
          UUPMediaConverter.exe -l en-US --uup-path .\$UupPath --iso-path "C:\workspace\Windows_Server_2022_${OSBuild}.iso"

      - name: Upload Windows ISO
        uses: actions/upload-artifact@v4
        with:
          name: Windows_Server_2022-iso
          path: C:\workspace\Windows_Server_2022_${{ env.OS_BUILD }}.iso
