name: Windows 2022 ISO
on:
  workflow_dispatch:
    inputs:
      os_build:
        description: OS build to use, or latest
        required: true
        default: latest
        type: string
jobs:
  build:
    name: Windows 2022 ISO
    runs-on: windows-2022

    steps:
      - name: Check out ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Select Windows OS build
        id: select_build
        shell: pwsh
        run: |
          $ChangeHistoryName = "Windows Server 2022"
          $UpdateJsonPath = Join-Path $Env:RUNNER_TEMP 'windows-server-2022-update.json'
          .\scripts\Get-WindowsUpdateHistory.ps1 -Name $ChangeHistoryName -Build '${{ inputs.os_build }}' -OutputPath $UpdateJsonPath | Out-Null
          $WindowsUpdate = Get-Content $UpdateJsonPath -Raw | ConvertFrom-Json
          $OSBuild = $WindowsUpdate.Build
          "os_build=$OSBuild" >> $Env:GITHUB_OUTPUT

          echo "::notice::Name: $ChangeHistoryName"
          echo "::notice::Metadata: $UpdateJsonPath"
          echo "::notice::Title: $($WindowsUpdate.Title)"
          echo "::notice::Build: $($WindowsUpdate.Build)"
          echo "::notice::KB: $($WindowsUpdate.KB)"
          echo "::notice::Link: $($WindowsUpdate.Link)"

      - name: Configure runner
        run: |
          docker system prune -a -f
          New-Item "C:\workspace" -ItemType Directory

      - name: Download UUP Media Creator
        shell: pwsh
        run: |
          $DownloadUrl = "https://github.com/gus33000/UUPMediaCreator/releases/download/v3.1.9.3/win-x64-binaries.zip"
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest $DownloadUrl -OutFile .\UUPMediaCreator.zip
          Expand-Archive -Path .\UUPMediaCreator.zip C:\UUPMediaCreator
          echo "PATH=$Env:PATH;C:\UUPMediaCreator" >> $Env:GITHUB_ENV

      - name: Download UUP files
        shell: pwsh
        working-directory: C:\workspace
        run: |
          $OSBuild = '${{ steps.select_build.outputs.os_build }}'
          $ReportingVersion = "10.0.${OSBuild}"
          UUPDownload.exe -s StandardServer -r Retail -b Retail -c fe_release -l en-US -t amd64 -v $ReportingVersion

      - name: Create Windows ISO
        shell: pwsh
        working-directory: C:\workspace
        run: |
          $OSBuild = '${{ steps.select_build.outputs.os_build }}'
          $UupPath = Get-Item .\10.0.*.*.* | Select-Object -First 1 -ExpandProperty Name
          UUPMediaConverter.exe -l en-US --uup-path .\$UupPath --iso-path "C:\workspace\Windows_Server_2022_${OSBuild}.iso"

      - name: Upload Windows ISO
        uses: actions/upload-artifact@v4
        with:
          name: Windows_Server_2022-iso
          path: C:\workspace\Windows_Server_2022_${{ steps.select_build.outputs.os_build }}.iso
